### ISSUE TITLE
Форма регистрации при первой авторизации (форма профиля)

### ISSUE THREAD

**Issue by Leningradez** [Piter-United/itgm#2]
Как **Участник ITGM**, хочу заполнить форму регистрации и выбрать интересные мне сообщества, чтобы меня пустили на мероприятие.

**Примечание**:
- предзаполнить форму данными из social network (через которую авторизовался)
- обязательно запросить проставить "основное сообщество"
- опционально - дать возможность выбрать доп. интересы (другие интересные сообщества)

---

**Набор полей для формы регистрации**:
- Фото - опционально - доставать при авторизации!
- ФИО * - доставать при авторизации!
- Email * - доставать при авторизации!
- Телефон (опционально) - доставать при авторизации!
- Компания * - возможно, доставать при авторизации!
- Специализация *
- Основное сообщество *
- Дополнительные сообщества (интересы) - опционально
- Опыт в IT * - до 1 года, 1-3 года, 3+ лет
- Несколько слов о себе и своей деятельности - опционально

**Comment by Realetive** [comment]
Delivered https://github.com/Piter-United/itgm/commit/e84414b3fae1000032b3bf8a9989dbc18757e17a
