### ISSUE TITLE
Интеграция с TmePad Piter United

### ISSUE THREAD

**Issue by Leningradez** [Piter-United/itgm#7]
Как **Волонтер на Регистрации**, хочу иметь возможность отмечать явку участника на ITGM используя инструментарий TimePad, чтобы можно было посчитать фактическое количество участников.

---

Как **Организатор ITGM**, хочу чтобы участники были оповещены о предстоящем слете, чтобы я мог делать по ним рассылку используя мощности TimePad.

---

Как **Участник ITGM**, хочу получить билет после регистрации на ITGM, чтобы предъявить его при входе на мероприятие.

===
**Задача**:
- сделать интеграцию Aidbox и Timepad через их Timepad API
- после регистрации у нас на платформе, скидывать информацию об участнике в Timepad
- чтобы Timepad высылал билеты, напоминал о мероприятии, позволял делать рассылки

**Comment by mike1pol** [comment]
Необходимо создать [aidbox app](https://docs.aidbox.app/aidbox-sdk/aidbox-apps) которая будет реализовывать `Subscription` на ресурс `UserProfile` и на *action* `create` создавать регистрацию пользователя в timepad

**Comment by Leningradez** [comment]
Timepad не дает такого API
