### ISSUE TITLE
Проблема в логике создания activity

### ISSUE THREAD

**Issue by alexsuslov** [Piter-United/itgm#97]
Открываем http://localhost:1234/activity
- нажимаем добавить тему
- форма пустая все ок
- открываем на чтение любую тему  все хорошо
- открываем опять добавить тему

у нас в редактировании тема которую мы смотрели
с возможностью сохранить данные

![Снимок экрана 2020-02-04 в 06 43 17](https://user-images.githubusercontent.com/3445074/73712047-ef22a100-4719-11ea-89d7-daa5556bc4d6.png)

**Comment by alexsuslov** [comment]
автор темы сменился на меня
![Снимок экрана 2020-02-04 в 06 46 16](https://user-images.githubusercontent.com/3445074/73712098-15484100-471a-11ea-9fa2-7f0b47fea41b.png)

**Comment by zipofar** [comment]
Попробуйте еще раз. Поправил вроде бы этот косяк

**Comment by alexsuslov** [comment]
Теперь при нажатии на кнопку создания, все залипает
